### ISSUE TITLE
Composer search doesn't seem to work

### ISSUE THREAD

**Issue by ngocphamm** [willfarrell/alfred-pkgman-workflow#54]
I don't know what would be the problem, but on my setup, it doesn't seem to work at all. Please see the quickcast.

Alfred version: 2.5.1
Package Manager version: 2.6

http://quick.as/e6Dgf6Gk

**Comment by willfarrell** [comment]
Good catch. Looks like some debug code was left in causing a hard coded query. Should be all fixed in v2.7. Thanks for letting me know.

**Comment by ngocphamm** [comment]
Thank you for the quick catch up!!! It still have a small issue with the description line, though.

The first 2 characters were stripped out.
![screen shot 2015-01-23 at 9 53 19 pm](https://cloud.githubusercontent.com/assets/395123/5885904/6a7568fc-a34a-11e4-8351-ce6052b11467.png)

I observed another "problem" with brew search. Should I open another issue?

**Comment by willfarrell** [comment]
Pushed v2.8 with the fix. Let me know if you find anything else. Thanks.

**Comment by ngocphamm** [comment]
:+1:  Many thanks for the super quick fix. I will report the problem with brew on another issue.
